export const GET_PRODUCTS = "GET_PRODUCTS";
export const TOGGLE_EDIT_MODAL = "TOGGLE_EDIT_MODAL";
export const TOGGLE_ADD_MODAL = "TOGGLE_ADD_MODAL";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
